dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "5.6"

env:
  - CONTAO_VERSION=contao/core-bundle ~4.4.0
  - CONTAO_VERSION=contao/core-bundle ~4.5.0
  - CONTAO_VERSION=contao/core-bundle ~4.6.0
  - CONTAO_VERSION=contao/core-bundle ~4.7.0
  - CONTAO_VERSION=contao/core-bundle ~4.8.0
  - CONTAO_VERSION=contao/core-bundle ~4.9.0
  - CONTAO_VERSION=contao/core-bundle ~4.10.0

# Exclude impossible Contao Version combinations.
matrix:
  fast_finish: true
  exclude:
    - php: 5.6
      env: CONTAO_VERSION=contao/core-bundle ~4.5.0
    - php: 5.6
      env: CONTAO_VERSION=contao/core-bundle ~4.6.0
    - php: 5.6
      env: CONTAO_VERSION=contao/core-bundle ~4.7.0
    - php: 5.6
      env: CONTAO_VERSION=contao/core-bundle ~4.8.0
    - php: 5.6
      env: CONTAO_VERSION=contao/core-bundle ~4.9.0
    - php: 7.1
      env: CONTAO_VERSION=contao/core-bundle ~4.9.0
    - php: 5.6
      env: CONTAO_VERSION=contao/core-bundle ~4.10.0
    - php: 7.1
      env: CONTAO_VERSION=contao/core-bundle ~4.10.0
  allow_failures:
    # Allow failure for the deprecated php 5.6 version.
    - php: "5.6"
    # The actual phpcq test generate a to long travis log. (The job exceeded the maximum log length, and has been terminated.)
    - php: "7.4"

before_install:
  - echo "memory_limit = -1" > travis.php.ini && phpenv config-add travis.php.ini

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer require $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

cache:
  directories:
    - vendor
