services:
    cca.legacy_dic:
        class: DependencyInjection\Container\LegacyDependencyInjectionContainer
        arguments: ["@contao.framework"]

    cca.legacy_dic.initializer:
        class: DependencyInjection\Container\ContainerInitializer

    DependencyInjection\Container\ContaoServices\Services:
        arguments: ["@service_container"]
    cca.legacy_dic.contao_config:
        class: DependencyInjection\Container\ContaoServices\Services
        factory: 'DependencyInjection\Container\ContaoServices\Services:createConfigService'
    cca.legacy_dic.contao_environment:
        class: DependencyInjection\Container\ContaoServices\Services
        factory: 'DependencyInjection\Container\ContaoServices\Services:createEnvironmentService'
    cca.legacy_dic.contao_user:
        class: DependencyInjection\Container\ContaoServices\Services
        factory: 'DependencyInjection\Container\ContaoServices\Services:createUserService'
    cca.legacy_dic.contao_database_connection:
        class: DependencyInjection\Container\ContaoServices\Services
        factory: 'DependencyInjection\Container\ContaoServices\Services:createDatabaseConnectionService'
    cca.legacy_dic.contao_input:
        class: DependencyInjection\Container\ContaoServices\Services
        factory: 'DependencyInjection\Container\ContaoServices\Services:createInputService'
    cca.legacy_dic.contao_session:
        class: DependencyInjection\Container\ContaoServices\Services
        factory: 'DependencyInjection\Container\ContaoServices\Services:createSessionService'
    cca.legacy_dic.contao_page_provider:
        class: DependencyInjection\Container\ContaoServices\Services
        factory: 'DependencyInjection\Container\ContaoServices\Services:createPageProviderService'
