services:
  legacy_container:
    class: Pimple
    factory: ['@pimple_container.provider', 'getContainer']

  legacy_container.provider:
    class: DependencyInjection\Container\DependencyInjection\LegacyContainerProvider
    arguments:
      - '@contao.framework'
