services:
    cca.legacy_dic:
        class: DependencyInjection\Container\LegacyDependencyInjectionContainer
        arguments: ["@contao.framework"]
        deprecated: ~

    cca.legacy_dic.initializer:
        class: DependencyInjection\Container\ContainerInitializer

    DependencyInjection\Container\ContaoServices\ServiceFactory:
        arguments: ["@service_container"]
    cca.legacy_dic.contao_config:
        class: Contao\Config
        factory: 'DependencyInjection\Container\ContaoServices\ServiceFactory:createConfigService'
        deprecated: 'The "%service_id%" service is deprecated. Use "contao.framework" createInstance() instead'
    cca.legacy_dic.contao_environment:
        class: Contao\Environment
        factory: 'DependencyInjection\Container\ContaoServices\ServiceFactory:createEnvironmentService'
        deprecated: 'The "%service_id%" service is deprecated. Use "contao.framework" createInstance() instead'
    cca.legacy_dic.contao_user:
        class: Contao\User
        factory: 'DependencyInjection\Container\ContaoServices\ServiceFactory:createUserService'
        deprecated: ~
    cca.legacy_dic.contao_database_connection:
        class: Contao\Database
        factory: 'DependencyInjection\Container\ContaoServices\ServiceFactory:createDatabaseConnectionService'
        deprecated: 'The "%service_id%" service is deprecated. Use the "database_connection" service instead'
    cca.legacy_dic.contao_input:
        class: Contao\Input
        factory: 'DependencyInjection\Container\ContaoServices\ServiceFactory:createInputService'
        deprecated: 'The "%service_id%" service is deprecated. Use "contao.framework" createInstance() instead'
    cca.legacy_dic.contao_session:
        class: Contao\Session
        factory: 'DependencyInjection\Container\ContaoServices\ServiceFactory:createSessionService'
        deprecated: 'The "%service_id%" service is deprecated. Use the session service instead'
    cca.legacy_dic.contao_page_provider:
        class: DependencyInjection\Container\PageProvider
        factory: 'DependencyInjection\Container\ContaoServices\ServiceFactory:createPageProviderService'
        deprecated: ~
